### ISSUE TITLE
Fix `addComments` feature (or docs)

### ISSUE THREAD

**Issue by opyh** [AlexMost/babel-plugin-polyglot#105]
The `addComments` config parameter seems not to work anymore in 1.1.0-0 (or the documentation is outdated).

When specifying `addComments: 'translator:'` as config option, the following comment will not be added to the `.pot` file: `// translator: Bla`. This is because the configured prefix needs to include the whitespace between `//` and `translator`. From my memory, this has worked before, and the documentation says it's supposed to work without specifying the space.

I'm using `addComments: ' translator:'` (note the space at the beginning of the string) as a workaround for now. Should we just update the docs and add the string there, or support whitespace in the matcher?

Thanks to everyone putting effort into maintaining this project, you rock! 👌🏻

**Comment by AlexMost** [comment]
Hey, thanks for the feedback! :heart: 
I think that is a bug, and we should omit spaces after `//` while matching. That one should be easy to fix.

**Comment by AlexMost** [comment]
version `1.1.0` is available with fix
