### ISSUE TITLE
Config.resolve.unresolved with default translations

### ISSUE THREAD

**Issue by hiousi** [AlexMost/babel-plugin-polyglot#126]
Don't know if it's the desired behaviour but when Config.resolve.unresolved is set to 'fail' and translations is set to 'default' an error is throw on compilation.
I would expect errors to be fired only for a translation coming from a po and not from 'default'.

**Comment by AlexMost** [comment]
Hi @hiousi! Thanks for the report. Seems like a bug, need to check that!

**Comment by AlexMost** [comment]
The fix is available in the `1.7.9` version of `babel-plugin-ttag` or `ttag-cli`. Let me know if that works.
