### ISSUE TITLE
Don't attach references to translation files - config object

### ISSUE THREAD

**Issue by mkosir** [AlexMost/babel-plugin-polyglot#130]
Hi, I'm working with CRA and I would like to have translated .po files without references included.
Can't figure out the way with babel plugin as stated [in the docs](https://github.com/ttag-org/ttag/blob/a25c11c82d395e56f14cfd96d853d442be1e9a48/docs/configuration.md#configextractlocation-string) `Config.extract.location` set to `never`.  
Idealy I would like to pass `[opts]` object to CLI but not sure if something like that is possible `npx ttag update [opts] i18n/en.po src/`?  
Is there maybe any example how CRA and ttag should be configured to achieve that .po files are without references?

**Comment by AlexMost** [comment]
Hi @mkosir! If I have got your point you can provide `-extractLocation=never` to update or extract cmd.  https://github.com/ttag-org/ttag-cli#extract-outputlang-src

**Comment by mkosir** [comment]
Thanks, works like a charm.
