### ISSUE TITLE
use plugin for validation but without translation

### ISSUE THREAD

**Issue by Suhoy95** [AlexMost/babel-plugin-polyglot#87]
Hello, 

I want to use c-3po-plugin to fetch `.po` files and validation translation, but i don't want transliteration of translation to the bundle.js . Instead of it i want to load language translation dynamically.

i don't find this case in docs explicitly. But I'll make experiment about this.

**Comment by AlexMost** [comment]
Hello,
from the `0.5.x` version c-3po-babel-plugin will be doing validation with no transpile by default. All you need is to just add it to babel plugin to the config without no configuration options.
