### ISSUE TITLE
gettext backwards

### ISSUE THREAD

**Issue by Suhoy95** [AlexMost/babel-plugin-polyglot#88]
Hello, 

I need to localize project with Russian lang. When i get English translation it'll be gread to switch **msgid** in sources to English ([the same issue](https://mail.python.org/pipermail/python-list/2007-May/447917.html)). 

With using babel and work with AST it sounds possible. How do you think this is real?
(i don't have a lot time to explore babel deeply, but if it's real i should try)

**Comment by AlexMost** [comment]
Hm, I have got your point, I think it's doable. I think it makes sense to implement this as a standalone utility based on `c-3po` internals.

**Comment by erickwilder** [comment]
In my humble opinion we should limit the features of localization as minimum as possible. This is not an official `gettext` feature and it looks much more like an app-specific requirement than something to bundle in a reusable library/plugin.

**Comment by AlexMost** [comment]
:+1:
