### ISSUE TITLE
Expression 'a[value]' is not found in the localized string '${ a[value] } banana ${ b[value] }'.

### ISSUE THREAD

**Issue by MrOrz** [AlexMost/babel-plugin-polyglot#90]
Seems that the current `validateAndFormatMsgid` does not support `[]` notations. The main reason is that we directly interpolate variable value when creating regular expressions. And `new Regexp('a[value]')` cannot match the string `a[value]`.

Added failing test case:
https://github.com/MrOrz/babel-plugin-c-3po/commit/dfdb5e154f458bba901a38ffea93ef84cc5bec41

Have not come up with a fix yet. Maybe we should not use regular expressions here...?

**Comment by AlexMost** [comment]
thanks, will look at this issue soon.

**Comment by AlexMost** [comment]
fixed in `0.5.7`
